### ISSUE TITLE
Build custom Matomo opt-out component

### ISSUE THREAD

**Issue by ohrie** [FixMyBerlin/rsv-dossier#26]
## What's the problem you want solved?
We currently use a Matomo Iframe for users to opt out from tracking. This is located at `/datenschutz` page. Since Iframes are not optimal, especially for mobile, we would like to get rid of the iframe and use the matomo script to build a opt-out component our self.

## Is there a solution you'd like to recommend?
There is a documentation at https://developer.matomo.org/guides/tracking-javascript-guide#optional-creating-a-custom-opt-out-form how to use the script.

## Tasks
- [ ] Remove the iframe from datenschutz page
- [ ] Create new component `MatomoOptOut`
- [ ] Use script mentioned above to build a checkbox which disables tracking on disabling.
